-- Tables

-- Create the SHAREHOLDERS table.
CREATE TABLE IF NOT EXISTS SHAREHOLDERS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    OWNERSHIP NUMERIC(5, 2) CHECK (OWNERSHIP > 0 AND OWNERSHIP <=100),
    INVESTMENT NUMERIC(15, 2) CHECK (INVESTMENT) >= 0,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    SHAREHOLDER_STATUS VARCHAR(20) DEFAULT 'active' CHECK (SHAREHOLDER_STATUS IN ('active', 'inactive')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);