-- Tables

-- Create the SHAREHOLDERS table.
CREATE TABLE IF NOT EXISTS SHAREHOLDERS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    OWNERSHIP NUMERIC(5, 2) CHECK (OWNERSHIP > 0 AND OWNERSHIP <=100),
    INVESTMENT NUMERIC(15, 2) CHECK (INVESTMENT >= 0),
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    SHAREHOLDER_STATUS VARCHAR(20) DEFAULT 'active' CHECK (SHAREHOLDER_STATUS IN ('active', 'inactive')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID SERIAL PRIMARY KEY,
    TICKER VARCHAR(10) NOT NULL,
    SHARES NUMERIC(10, 2) CHECK (SHARES > 0),
    PRICE_PER_SHARE NUMERIC(15, 2) CHECK (PRICE_PER_SHARE > 0),
    TOTAL_VALUE NUMERIC(20, 2) GENERATED ALWAYS AS (SHARES * PRICE_PER_SHARE) STORED,
    TRANSACTION_TYPE VARCHAR(10) NOT NULL CHECK (TRANSACTION_TYPE IN ('buy', 'sell')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);