DROP TABLE IF EXISTS SHAREHOLDERS CASCADE;
DROP TABLE IF EXISTS FIRM CASCADE;
DROP TABLE IF EXISTS TRANSACTIONS CASCADE;
DROP TABLE IF EXISTS PORTFOLIO CASCADE;
DROP TABLE IF EXISTS HISTORY;

DROP TRIGGER IF EXISTS after_live_update ON PORTFOLIO;
DROP TRIGGER IF EXISTS after_buy_transaction ON TRANSACTIONS;
DROP TRIGGER IF EXISTS after_sell_transaction ON TRANSACTIONS;

SELECT tgname
FROM pg_trigger
WHERE tgrelid = 'portfolio'::regclass;