from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, Any, Dict

@dataclass
class BaseModel:
    """
    A flexible base model that can handle arbitrary attributes.
    """

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert the instance attributes to a dictionary.
        """
        return self.__dict__

    def __repr__(self) -> str:
        """
        Custom string representation for debugging.
        """
        fields = ', '.join(f"{key}={value!r}" for key, value in self.to_dict().items())
        return f"{self.__class__.__name__}({fields})"

@dataclass
class ShareholderModel(BaseModel):
    """
    Model representing a shareholder.
    """
    name: str # Shareholder name
    ownership: float # Ownership percentage
    investment: float # Amount invested
    email: str # Shareholder email
    id: Optional[int] = None # Shareholder ID
    shareholder_status: Optional[str] = None # Shareholder status 'active' by default
    created: Optional[datetime] = None # Shareholder creation timestamp

@dataclass
class TransactionsModel(BaseModel):
    """ 
    Model representing an asset transaction.
    """
    firm_id: Optional[int] # Firm ID
    ticker: str # Stock ticker
    shares: int # Number of shares
    price_per_share: float # pps 
    transaction_type: str # 'buy' or 'sell'
    total: Optional[float] = field(default=None, compare=False) # Total cost, generated by database
    id: Optional[int] = None # Transaction ID
    timestamp: Optional[datetime] = None # Transaction timestamp
    
@dataclass
class FirmModel(BaseModel):
    """ 
    Model representing a firm table.
    """
    total_value: float
    total_value_investments: float
    cash_reserve: float
    net_profit: float
    net_loss: float
    id: Optional[int] = None
    created: Optional[datetime] = None
    
@dataclass
class PortfolioModel(BaseModel):
    """ 
    Model representing a portfolio of assets.
    """
    firm_id: int
    ticker: str
    shares: int
    average_purchase_price: float
    total_invested: float
    realized_profit_loss: float
    current_price: float
    total_value: float
    unrealized_profit_loss: float
    dividend_yield_percentage: float
    dividend_yield_amount: float
    total_dividends_received: float
    last_updated: Optional[datetime] = None
    